---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
  namespace: quarkus-application
  labels:
    app: demo
spec:
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
        - name: demo
          image: kyouuma/quarkus-native-development
          ports:
            - name: demo
              containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: demo
  namespace: quarkus-application
  labels:
    app: demo
spec:
  type: ClusterIP
  ports:
    - name: demo
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: demo

---

apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: demo-ingress
  namespace: quarkus-application
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
    - host: quarkus.kyoumatrix.io
      http:
        paths:
          - backend:
              serviceName: demo
              servicePort: 80
            path: /

---



